services:
  - type: web
    name: pdf-master-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: NODE_VERSION
        value: 20.11.0